Added troubleshooting section.
nemtech/symbol-docs pull request #564
Opened 2021-01-13 17:32 UTC by mm-s

Added known problem and workaround (user's permissions for docker daemon).

2021-01-13 18:26 UTC, segfaultxavi requested changes
First off, thanks a lot for submitting a docs pull request!

In the Conversation tab of this PR, at the bottom you'll see a `netlify/nemtech/deploy-preview` line. If you click on the `Details` link you'll see a preview of your PR (after navigating to the page you modified). There you'll spot some rendering errors (like the bullet point in a single line). This is extremely helpful, in case you don't have a local Sphinx installation to check everything before submitting.

The new **Troubleshooting** section is after the **Next steps** section, which should always be the last one.

But foremost, I don't think a single entry warrants a whole new section. In this case, I would resolve this issue with a note at the end of the **Creating a configuration file** section. Something similar to:

```
.. note:: If you get the error ``Permission denied while trying to connect to the Docker daemon socket`` it means that your user does not belong to the docker group. Add it with:

  .. code-block:: bash

    sudo addgroup <YOUR-USERNAME> docker
```

If we start adding too many notes like this one then we can add a **Troubleshooting** section.

2021-01-14 11:41 UTC, mm-s commented
Thanks for the review Xavi. I think you're right, a note is more appropriate than creating a new section. I have added your suggested modifications.

2021-01-14 11:50 UTC, segfaultxavi approved these changes
Awesome, thanks!

2021-01-14 11:50 UTC, segfaultxavi commented on source/guides/network/using-symbol-bootstrap.rst
> +
```suggestion
```

2021-01-14 11:51 UTC, merged